### ISSUE TITLE
MyTestNull?

### ISSUE THREAD

**Issue by AlexMouton** [justinwoo/purescript-simple-json#11]
https://github.com/justinwoo/purescript-simple-json/blob/71079decfbb6efe30e62524d54661ea563236e7d/test/Main.purs#L73

Hi Justin et al.
Should this be MyTestNull here?

**Comment by justinwoo** [comment]
ah, wording is confusing but that one is the "lacking" case, the "contains" case is the next one over

**Comment by AlexMouton** [comment]
Hi justin
It seems to me that the test should be a json record excluding 'e' vs a record that conditionally expects it.  Json without e and record without e is no test?

**Comment by justinwoo** [comment]
oh, i see what you're saying now. yeah, i guess it should be that way and should be fixed

**Comment by jacereda** [comment]
Fixed, thanks!

**Comment by AlexMouton** [comment]
Sorry for such minor corrections.
Just barely getting familiar with purescript now.
Hopefully I can find some larger issues for you guys soon ;)

Thanks!
A
