### ISSUE TITLE
Flesh out docs/examples in docs directory

### ISSUE THREAD

**Issue by f-f** [justinwoo/purescript-simple-json#23]
I tripped up while following the example usage in README, and noticed that the linked `telegram-bot` repo might be outdated wrt the latest version of this lib - most notably, since `readJSON` returns a nice `Either`, the example usage should contain it explicitly instead of `IO` and `F`.

I'll give a try to put together a "beginner-friendly" example section PR.

**Comment by justinwoo** [comment]
This issue is now converted to being about making sure all of the relevant examples and write up go into the docs/ directory as built by readthedocs: http://purescript-simple-json.readthedocs.io/en/latest/

**Comment by justinwoo** [comment]
We should actually define some concrete goals in this issue and maybe make a "Milestone"

**Comment by justinwoo** [comment]
https://github.com/justinwoo/purescript-simple-json/milestones

**Comment by justinwoo** [comment]
Basically done
