### ISSUE TITLE
Only first error is taken into account

### ISSUE THREAD

**Issue by hrajchert** [justinwoo/purescript-simple-json#36]
Hi! Thanks for the library, it's awesome!

Currently I'm facing a problem where I see that only the first error is reported, which I think is a little counter intuitive considering that the signature of readJson has `MultipleErrors` for error handling.

This is the complete main file i'm testing

```purescript
module Main where

import Prelude
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (CONSOLE, log)
import Simple.JSON (readJSON, readJSON')
import Data.Either (Either(..))
import Data.Foreign (F, MultipleErrors)
import Control.Monad.Except (runExcept)

type TestJson =
  { a :: String
  , b :: String
  }


correctJson =
  """
  {"a": "a", "b": "b"}
  """

incorrectJson = "{}"

parseTest :: String -> Either MultipleErrors TestJson
parseTest = readJSON

parseTest' :: String -> F TestJson
parseTest' = readJSON'

main :: forall e. Eff (console :: CONSOLE | e) Unit
main = do
  case (parseTest incorrectJson) of
    Right test -> log $ test.a
    Left err   -> log $ show err
  case (runExcept $ parseTest' incorrectJson) of
    Right test -> log $ test.a
    Left err   -> log $ show err
```

and the console outputs

```
> pulp run
(NonEmptyList (NonEmpty (ErrorAtProperty "a" (TypeMismatch "String" "Undefined")) Nil))
(NonEmptyList (NonEmpty (ErrorAtProperty "a" (TypeMismatch "String" "Undefined")) Nil))
```

I was expecting both **a** and **b** to be reported missing.

Thanks!

**Comment by justinwoo** [comment]
The [ExceptT](https://pursuit.purescript.org/packages/purescript-transformers/3.6.0/docs/Control.Monad.Except.Trans) type and its instances means that only alternative and such accumulate multiple errors. You're looking for something this library doesn't do, which is to continue parsing in applicative validation style: https://pursuit.purescript.org/packages/purescript-validation/3.2.0

**Comment by hrajchert** [comment]
I didn't get all that (still new on this), but shouldn't the signature be

```purescript
readJSON :: forall a. ReadForeign a => String -> Either ForeignError a
```

instead of MultipleErrors?

**Comment by justinwoo** [comment]
If you try an example where you have an alternative, then you will see that are multiple errors accumulated.

**Comment by justinwoo** [comment]
Could you ask somewhere like #purescript-beginners on FP slack? The issues here should be for bugs.

**Comment by hrajchert** [comment]
Sure, will do
