### ISSUE TITLE
Needs a quick start guide in docs

### ISSUE THREAD

**Issue by justinwoo** [justinwoo/purescript-simple-json#42]
Should probably be written by someone other than me. Maybe the only thing that really needs to be covered is

```purs
main = do
  let e = JSON.readJSON "1"
  case e of
    Right (x :: Int) -> -- ...
```

**Comment by jkachmar** [comment]
I'll take this, meant to do it before, got distracted.

**Comment by justinwoo** [comment]
Fixed a while ago with the quickstart guide
