### ISSUE TITLE
How to handle arbitrary String Maps/JSON

### ISSUE THREAD

**Issue by i-am-the-slime** [justinwoo/purescript-simple-json#53]
I'm in a server setting. I find myself needing to route through some dynamic parts of a 3.6MB JSON response to the caller. So something like a field `attributes :: Array JsonValue`. Can I do this with simple-json?

**Comment by justinwoo** [comment]
I don't know what you're trying to do or how you'd accomplish this in JS normally. If the JSON values are individual values per line, then you will want to split up your input by lines.

**Comment by i-am-the-slime** [comment]
I mean some JSON like this:
```json
{  
  "known_field": 4,
  "known_field_2": "bla",
  "additional_dynamic_attributes": [
    "unknown_attribute_1": { "key": "value"},
    "unknown_attribute_2": 5,
    ... more of these
  ]
}
```

**Comment by i-am-the-slime** [comment]
Imagine I get something like this as a response from an API call. I don't care about these attributes, I just want to proxy them to whoever called my service.

**Comment by justinwoo** [comment]
Do you want to type that as `Foreign.Object.Object Foreign` and pass it through? Do you want to call `parseJSON` to only parse it from a String to Foreign to pass through?

**Comment by i-am-the-slime** [comment]
Ah! I think `Foreign.Object.Object Foreign` is probably the solution I was looking for!
