### ISSUE TITLE
Use ErrorAtIndex

### ISSUE THREAD

**Issue by reactormonk** [justinwoo/purescript-simple-json#57]
The library uses `ErrorAtProperty` for record decoding, but it could also use `ErrorAtIndex` for Arrays.

```
> runExceptT $ readJSON' "{ \"foo\": [\"bar\", \"baz\", 3] }" :: F { foo :: Array String }
(Identity (Left (NonEmptyList (NonEmpty (ErrorAtProperty "foo" (TypeMismatch "String" "Number")) Nil))))
```

**Comment by justinwoo** [comment]
That's a problem for purescript-foreign: https://pursuit.purescript.org/packages/purescript-foreign/5.0.0/docs/Foreign#v:ErrorAtProperty

**Comment by reactormonk** [comment]
Shouldn't simple-json attach that information [here](https://github.com/justinwoo/purescript-simple-json/blob/master/src/Simple/JSON.purs#L166)?

```
> runExceptT $ readJSON' "{ \"foo\": [\"bar\", \"baz\", 3] }" :: F { foo :: Array String }
(Identity (Left (NonEmptyList (NonEmpty (ErrorAtProperty "foo" (TypeMismatch "String" "Number")) Nil))))
```

**Comment by justinwoo** [comment]
admittedly this has started to annoy me, so i have to fix this sometime soon

**Comment by justinwoo** [comment]
https://github.com/justinwoo/purescript-simple-json/commit/200ba88e74aa3cdc040d62154e0d0c7152a38b72
