### ISSUE TITLE
Creating enumWriteForeign?

### ISSUE THREAD

**Issue by Cmdv** [justinwoo/purescript-simple-json#68]
I've created an `enumReadForeign` from reading the docs but I'm wondering if I would have to do something similar to account for the `from` or is there a simpler way?

**Comment by justinwoo** [comment]
yeah i think you're going to be stuck with writing it out manually, unless you come up with some kind of bidirectional thing. but this is also where i ended up using my other library for converting sums to variant and such to use the inferred instances: https://github.com/justinwoo/purescript-kishimen#usage

**Comment by justinwoo** [comment]
probably this should be mentioned somewhere in the docs but im a bit too lazy

**Comment by Cmdv** [comment]
hahaha that's all good can't write everything. Ah nice you have `genericSumToVariant` that's perfect was more interested in getting type safety for these sum types when throwing them to and from an external API. Thank 👍

**Comment by Cmdv** [comment]
oh a side note I could do something like you did here

https://github.com/adamczykm/purescript-sentry-raven/blob/fd82dce103912cbd404f04932f3bd523e3f88307/src/SentryRaven/Breadcrumb.purs#L34-L39
