### ISSUE TITLE
writeJson

### ISSUE THREAD

**Issue by justinwoo** [justinwoo/purescript-simple-json#8]
This library really needs a write Json implementation.

@paf31 is it okay with you if I write an implementation into this library? I feel like it might not be kosher for me to just put it in here since I saw your implementation first.

**Comment by justinwoo** [comment]
Ah, seems like we will need to do a lot of work anyway so my concerns about being a copycat implementation are probably unfounded.

**Comment by paf31** [comment]
I'm not sure which code of mine you're referring to 😄

**Comment by justinwoo** [comment]
You had a stringify implementation a while back that checked the types of the fields, but in our case we need to actually write to Foreign since we support non-primitive types

**Comment by justinwoo** [comment]
Implemented!
